### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by rodrigofaccioli** [jtpio/trello-full-backup#10]
Dear all,

Thanks for your program.

I've installed it using pip program in Ubuntu 16.10. I followed all instructions to install it. However, when I ran trello-full-backup the error message is showed: TypeError: 'encoding' is an invalid keyword argument for this function. The program is started correctly because I received in my prompt:
==== Backup initiated
('Backing up to:', '2017-05-11_13-19-55_backup')
('Backup closed board:', False)
('Backup archived lists:', False)
('Backup archived cards:', False)
('Attachment size limit (bytes):', 100000000)
==== 
More specific, my error message is:
()
('Saving full json for board', u'Alexandre Defelicibus', 'with id', u'54df5c6b38dc68c0fd0201c9', 'to', 'Alexandre Defelicibus_full.json')
Traceback (most recent call last):
  File "/usr/local/bin/trello-full-backup", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/trello_full_backup/__init__.py", line 5, in main
    cli()
  File "/usr/local/lib/python2.7/dist-packages/trello_full_backup/backup.py", line 247, in cli
    backup_board(board, args)
  File "/usr/local/lib/python2.7/dist-packages/trello_full_backup/backup.py", line 125, in backup_board
    write_file(file_name, board_details)
  File "/usr/local/lib/python2.7/dist-packages/trello_full_backup/backup.py", line 33, in write_file
    with open(file_name, 'w', encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

I appreciate any help.

Best regards,

**Comment by jtpio** [comment]
Thanks for the report.
I can see from your logs that you are using Python 2.7 (`/usr/local/lib/python2.7/`).
And this script is **only compatible with Python 3.4+**.

If you get the chance to install Python 3.4 on your system or in a virtual environment, give it another try.
Otherwise, there is a Docker image which abstracts away the version of Python and can be used directly as long as you can run Docker on your system.

**Comment by rodrigofaccioli** [comment]
@jtpio thanks for you comment. I'll try it.

**Comment by rodrigofaccioli** [comment]
@jtpio 
According to your suggestion, I've used Docker image and it worked well. 
Thanks your attention.
Best regards,

**Comment by jtpio** [comment]
Glad it worked!
If you have the possibility to upgrade your Python to 3.6 on your system, feel free to do so ;)
