### ISSUE TITLE
Refactor as a python module

### ISSUE THREAD

**Issue by robinbowes** [jtpio/trello-full-backup#4]
It would be great (and easier to use this code) if you were to refactor it as a python module, so we can eg. `pip install trello-full-backup`

**Comment by jtpio** [comment]
Totally agree! Will be taking care of that very soon.

**Comment by jtpio** [comment]
Fixed: https://pypi.python.org/pypi/trello-full-backup

**Comment by robinbowes** [comment]
Great, thanks!

I shall follow up with a PR to separate the code that actually does the backup from the arg processing and general CLI setup.
